on: push


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn compile --batch-mode

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn test --batch-mode

  build-jar-file:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn test --batch-mode

    sca-scan-trivy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v4
        - name: Run Trivy vulnerability scanner
        - uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'table'
            exit-code: 1
            severity: 'CRITICAL,HIGH'
