on: push

setup-java: &setup-container
  uses: actions/checkout@v4
  uses: actions/setup-java@v4
  with:
    java-version: "23"
    distribution: "temurin"
    cache: 'maven'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - *setup-container
      - run: mvn compile --batch-mode

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - *setup-container
      - run: mvn test --batch-mode

  build-jar-file:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - *setup-container
      - run: mvn test --batch-mode

sca-scan-trivy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v4

    # Installiere und führe den Trivy-Scan für das Repository aus
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'  # Scan das Filesystem (Code & Abhängigkeiten)
        ignore-unfixed: true
        format: 'table'
        exit-code: 1  # Falls Schwachstellen gefunden werden, schlägt der Job fehl
        severity: 'CRITICAL,HIGH'  # Prüft nur kritische & hohe Schwachstellen
