on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: cat /home/runner/.m2/settings.xml
      - run: mvn compile --batch-mode

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: cat /home/runner/.m2/settings.xml
      - run: mvn test --batch-mode

