on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn compile --batch-mode

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn test --batch-mode

  build-jar-file:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: 'maven'
      - run: mvn package --batch-mode
      - name: Upload Build Artifact (target)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/

  sca-scan-trivy:
    runs-on: ubuntu-latest
    needs: build-jar-file
    steps:
      - uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - run: ls -la
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: 1
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          scan-ref: "${{ github.workspace }}"  # Das gesamte Workspace scannen
          extra-options: "--scanners vuln"

